name: "Server Deployment"
on:
  pull_request:
    types:
      - opened
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2 on master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: ./
          REMOTE_HOST: ec2-44-215-126-12.compute-1.amazonaws.com
          REMOTE_USER: ec2-user
          TARGET: /var/www/html
