name: "QA Server Deployment"
on: workflow_dispatch
jobs:
  QA:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: index.html
          REMOTE_HOST: 18.204.6.196
          REMOTE_USER: ec2-user
          TARGET: /var/www/html
